theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette:
    primary: indigo  # 可选：添加主题颜色
  language: zh
  site_url: https://umnooob.github.io/course-demo/

site_name: 深度学习平台和应用（2025春）
nav:
  - 主页: "index.md"
  - 实验一: 
    - 1.1 实验说明: "lab1/实验一介绍.md"
    - 1.2 实验任务一：环境配置: "lab1/环境配置指南.md"
    - 1.3 实验任务二：PyTorch练习: "lab1/实验一代码.md"
    

markdown_extensions:
  - toc:
      permalink: True
  - footnotes
  - tables
  - admonition  # 提示块
  - pymdownx.details  # 提示块可折叠
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list  # 支持添加属性

# extra:
#   consent:
#     actions:
#       - download
