theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette:
    primary: indigo  # 可选：添加主题颜色
  language: zh
  site_url: https://umnooob.github.io/course-demo

site_name: NJU机器学习实验
nav:
  - 主页: "index.md"
  - 实验1: 
    - 实验一介绍: "lab1/实验一介绍.md"
    - 环境配置指南: "lab1/环境配置指南.md"
    

markdown_extensions:
  - toc:
      permalink: True
  - footnotes
  - tables
  - admonition  # 提示块
  - pymdownx.details  # 提示块可折叠
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list  # 支持添加属性

# extra:
#   consent:
#     actions:
#       - download
